// =============================================================================
// Intelligence & Recommendation Types
// =============================================================================

// =============================================================================
// Scoring
// =============================================================================

/**
 * Configurable per-user weights for each scoring factor.
 * All weights should sum to ~1.0.
 */
export interface ScoringWeights {
  draw_odds: number;
  trophy_quality: number;
  success_rate: number;
  cost_efficiency: number;
  access: number;
  forecast: number;
  personal_fit: number;
  timeline_fit: number;
}

/**
 * Individual factor scores, each normalized 0.0 to 1.0.
 */
export interface ScoringFactors {
  draw_odds_score: number;
  trophy_quality_score: number;
  success_rate_score: number;
  cost_efficiency_score: number;
  access_score: number;
  forecast_score: number;
  personal_fit_score: number;
  timeline_fit_score: number;
}

// =============================================================================
// Cost & Timeline Estimates
// =============================================================================

export interface CostEstimate {
  tag: number;
  license: number;
  points: number;
  travel: number;
  gear: number;
  total: number;
  /**
   * True when the cost was computed using state-specific fee data; false
   * (or undefined for legacy rows) when it fell back to the default
   * COST_CONFIG values. Lets the UI label the figure as an estimate vs.
   * a precise quote and tells ops which states still need fee seeding.
   */
  isExact?: boolean;
}

export interface TimelineEstimate {
  earliest: string;
  expected: string;
  latest: string;
}

export interface ConfidenceLevel {
  score: number;
  label: "high" | "medium" | "low";
  basis: string;
}

// =============================================================================
// Hunt Candidates & Scored Hunts
// =============================================================================

/**
 * A potential hunt opportunity before scoring.
 * Generated by candidate-generator from the universe of available hunts.
 */
export interface HuntCandidate {
  /** State UUID */
  stateId: string;
  stateCode: string;
  stateName: string;

  /** Species UUID */
  speciesId: string;
  speciesSlug: string;
  speciesName: string;

  /** Hunt unit UUID (optional — some recs are state/species level) */
  huntUnitId: string | null;
  unitCode: string | null;
  unitName: string | null;

  /** Unit characteristics */
  publicLandPct: number | null;
  terrainClass: string | null;
  elevationMin: number | null;
  elevationMax: number | null;

  /** Draw info */
  hasDraw: boolean;
  hasOtc: boolean;
  hasPoints: boolean;
  pointType: string | null;
  weaponTypes: string[];

  /** Latest draw odds snapshot (if available) */
  latestDrawRate: number | null;
  latestMinPoints: number | null;
  latestMaxPoints: number | null;
  latestAvgPoints: number | null;
  totalApplicants: number | null;
  totalTags: number | null;

  /** Latest harvest stats snapshot (if available) */
  latestSuccessRate: number | null;
  trophyMetrics: Record<string, unknown> | null;

  /** Season info */
  tagType: string | null; // 'draw' | 'otc' | 'leftover'
  seasonName: string | null;
  seasonStart: string | null;
  seasonEnd: string | null;

  /** Estimated cost */
  estimatedCost: CostEstimate;

  /** Estimated drive hours from home state */
  estimatedDriveHours: number | null;

  /** Metadata about how this candidate was generated */
  filtersApplied: string[];
}

/**
 * A hunt candidate with all scores computed.
 */
export interface ScoredHunt extends HuntCandidate {
  /** Individual factor scores */
  factors: ScoringFactors;

  /** Weights used for scoring */
  weightsUsed: ScoringWeights;

  /** Composite score (weighted sum of factors) */
  compositeScore: number;

  /** Rank among all scored candidates */
  rank: number;

  /** Confidence assessment */
  confidence: ConfidenceLevel;

  /** Timeline classification */
  timelineCategory: "this_year" | "1-3_years" | "3-5_years" | "5+_years";

  /** Recommendation type */
  recType: "apply_now" | "build_points" | "otc_opportunity" | "watch";
}

// =============================================================================
// Recommendation Output
// =============================================================================

/**
 * Final recommendation with rationale, confidence, and cost estimates.
 */
export interface RecommendationOutput {
  /** DB ID once persisted */
  id?: string;

  /** The scored hunt data */
  hunt: ScoredHunt;

  /** AI-generated plain-English rationale */
  rationale: string;

  /** Cost breakdown */
  costEstimate: CostEstimate;

  /** Timeline estimate */
  timelineEstimate: TimelineEstimate;

  /** Confidence */
  confidence: ConfidenceLevel;

  /** ROI analysis (if computed) */
  roi?: ROIAnalysis;

  /** Forecast data (if computed) */
  forecast?: ForecastData;

  /** User orientation this was optimized for */
  orientation: "trophy" | "opportunity" | "balanced" | "meat" | "experience";

  /** Status */
  status: "active" | "saved" | "dismissed" | "applied";
}

// =============================================================================
// Strategy & Playbook
// =============================================================================

/**
 * Individual strategy recommendation within a playbook section.
 */
export interface StrategyRecommendation {
  hunt: ScoredHunt;
  rationale: string;
  priority: "high" | "medium" | "low";
  actionRequired: string;
  deadline: string | null;
  estimatedCost: CostEstimate;
  confidence: ConfidenceLevel;
}

export interface PointStrategyItem {
  stateId: string;
  stateCode: string;
  stateName: string;
  speciesId: string;
  speciesName: string;
  currentPoints: number;
  pointType: string;
  recommendation: "apply_now" | "build_points" | "hold" | "consider_exit";
  rationale: string;
  forecast: ForecastData | null;
  annualCost: number;
  projectedYearsToTag: number | null;
}

export interface BudgetAllocation {
  totalBudget: number;
  allocations: {
    category: string;
    amount: number;
    description: string;
  }[];
  unallocated: number;
}

/**
 * Output of the strategy optimizer.
 */
export interface StrategyPlan {
  nearTerm: StrategyRecommendation[];
  midTerm: StrategyRecommendation[];
  longTerm: StrategyRecommendation[];
  pointStrategy: PointStrategyItem[];
  budgetAllocation: BudgetAllocation;
  totalEstimatedCost: number;
  warnings: string[];
}

/**
 * A playbook section grouping (used in the playbook structure).
 */
export interface PlaybookSection {
  goals: string;
  nearTerm: RecommendationOutput[];
  longTerm: RecommendationOutput[];
  pointStrategy: PointStrategyItem[];
  budgetAllocation: BudgetAllocation;
}

/**
 * Complete playbook structure — the primary product output.
 */
export interface PlaybookData {
  id: string;
  version: number;
  generatedAt: string;

  // Hunter context
  goalsSummary: string;
  profileSnapshot: Record<string, unknown>;

  // Strategy sections
  executiveSummary: string;
  nearTerm: RecommendationOutput[];
  midTerm: RecommendationOutput[];
  longTerm: RecommendationOutput[];

  // Point strategy
  pointStrategy: PointStrategyItem[];

  // Budget
  budgetAllocation: BudgetAllocation;

  // Deadlines
  upcomingDeadlines: {
    state: string;
    species: string;
    deadlineType: string;
    date: string;
    actionRequired: string;
  }[];

  // Metadata
  confidenceSummary: string;
  dataSourcesUsed: string[];
  assumptions: string[];
}

// =============================================================================
// ROI Analysis
// =============================================================================

export interface ROIAnalysis {
  totalEstimatedCost: CostEstimate;
  expectedDrawProbability: number;
  expectedSuccessRate: number;
  costPerOpportunity: number;
  pointInvestmentToDate: number;
  sunkCostNote: string;
  roiScore: number;
  comparisonNote: string;
  recommendation: "strong_buy" | "buy" | "hold" | "consider_exit" | "exit";
}

export interface CostComparison {
  huntA: ScoredHunt;
  huntB: ScoredHunt;
  costDifference: number;
  valueDifference: number;
  betterValue: "a" | "b" | "equal";
  explanation: string;
}

// =============================================================================
// Forecast Data
// =============================================================================

export interface ForecastData {
  stateId: string;
  stateCode: string;
  speciesId: string;
  speciesName: string;
  unitId: string | null;
  unitCode: string | null;

  /** Historical data points used */
  historicalData: { year: number; value: number }[];

  /** Trend analysis */
  trend: "rising" | "stable" | "declining";
  trendStrength: number; // r-squared or similar 0-1

  /** Projections */
  projections: {
    year: number;
    projected: number;
    lowerBound: number;
    upperBound: number;
  }[];

  /** Confidence in the forecast */
  confidence: ConfidenceLevel;
  assumptions: string[];
}

export interface DrawOddsForecast {
  stateId: string;
  speciesId: string;
  unitId: string | null;
  userPoints: number;

  /** Probability of drawing at 1, 3, 5 year horizons */
  yearOne: { probability: number; confidence: number };
  yearThree: { probability: number; confidence: number };
  yearFive: { probability: number; confidence: number };

  /** Cumulative probability of drawing within N years */
  cumulativeProbability: {
    withinOneYear: number;
    withinThreeYears: number;
    withinFiveYears: number;
  };

  trend: "improving" | "stable" | "worsening";
  explanation: string;
}

export interface PointValueAssessment {
  stateId: string;
  stateCode: string;
  speciesId: string;
  speciesName: string;
  currentPoints: number;

  /** Estimated years until drawable */
  estimatedYearsToTag: number | null;

  /** Total future investment needed */
  totalFutureInvestment: number;

  /** Is it worth continuing? */
  verdict: "continue" | "hold" | "exit";
  verdictRationale: string;

  /** What you could do instead */
  alternativeUse: string;

  /** Break-even analysis */
  breakEvenPointThreshold: number | null;
}

// =============================================================================
// Default Weights — values live in config.ts, re-exported here for convenience
// =============================================================================

import { SCORING_CONFIG } from "./config";

export const DEFAULT_WEIGHTS: ScoringWeights = SCORING_CONFIG.defaultWeights;

/**
 * Orientation-adjusted weight presets.
 * The actual values are centralized in config.ts.
 */
export const ORIENTATION_WEIGHTS: Record<string, Partial<ScoringWeights>> = {
  ...SCORING_CONFIG.orientationWeights,
  balanced: { ...SCORING_CONFIG.defaultWeights } as ScoringWeights,
};
